---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: demo-cicd
  labels:
    app: demo-cicd
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo-cicd
  template:
    metadata:
      namespace: demo
      labels:
        app: demo-cicd
    spec:
      containers:
        - name: demo-cicd
          image: monx/demo-cicd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: demo-cicd-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: demo-cicd
  type: ClusterIP
---
apiVersion: apps/v1
kind: Ingress
metadata:
  namespace: demo
  name: demo-cicd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: demo-cicd.osones.com
      http:
        paths:
          - backend:
              serviceName: demo-cicd-svc
              servicePort: 80
